name: cartesia_tts
description: "Cartesia TTS."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  
  flutter:
    sdk: flutter

  flutter_soloud:
    git:
      url: git@github.com:alnitak/flutter_soloud.git
      ref: websocket

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logging: ^1.3.0

  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.5.7
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
